name: Tests

on:
  push:
    branches:
      - main
      - master
      - dev/*
  pull_request:
    branches:
      - main
      - master
      - dev/*
  workflow_dispatch:

jobs:
  call-tests:
    name: Extension tests
    uses: phpbb-extensions/test-framework/.github/workflows/tests.yml@3.3.x
    with:
      EXTNAME: vinny/multiavatar
      PHPBB_BRANCH: '3.3.x'
      EPV: 1
      EXECUTABLE_FILES: 1
      IMAGE_ICC: 1
      SNIFF: 1
      RUN_MYSQL_JOBS: 1
      RUN_PGSQL_JOBS: 0
      RUN_MSSQL_JOBS: 0
      RUN_WINDOWS_JOBS: 0
      RUN_COMPOSER_INSTALL: 1
      RUN_NPM_INSTALL: 0
      RUN_FUNCTIONAL_TESTS: 0
      PRIMARY_PHP_VERSION: '7.4'
      PHP_VERSION_MATRIX: '["7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]'
